### ISSUE TITLE
The latest version of Sensor fails to start with ClassNotFound error

### ISSUE THREAD

**Issue by nimkar** [oneops/sensor#43]
The latest version of Sensor seems to be broken. It fails to start with a ClassNotFound error. Hence no graphs or metrics can be seen in OneOps. Below is the error.

2017-04-24 22:15:51 [localhost-startStop-1] WARN org.springframework.web.context.support.XmlWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'oneOpsConfig': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.springframework.core.env.Environment com.oneops.config.OneOpsConfig.env; nested exception is org.springframework.beans.factory.CannotLoadBeanClassException: Error loading class [com.oneops.sensor.listeners.BasicListener] for bean with name 'basicListener' defined in ServletContext resource [/WEB-INF/application-context.xml]: problem with class file or dependent class; nested exception is java.lang.NoClassDefFoundError: com/espertech/esper/client/UpdateListener
Related cause: org.springframework.beans.factory.CannotLoadBeanClassException: Error loading class [com.oneops.sensor.listeners.BasicListener] for bean with name 'basicListener' defined in ServletContext resource [/WEB-INF/application-context.xml]: problem with class file or dependent class; nested exception is java.lang.NoClassDefFoundError: com/espertech/esper/client/UpdateListener
Related cause: org.springframework.beans.factory.CannotLoadBeanClassException: Error loading class [com.oneops.sensor.listeners.OpsEventListener] for bean with name 'opsEventListener' defined in ServletContext resource [/WEB-INF/application-context.xml]: problem with class file or dependent class; nested exception is java.lang.NoClassDefFoundError: com/espertech/esper/client/UpdateListener
Related cause: org.springframework.beans.factory.CannotLoadBeanClassException: Error loading class [com.oneops.sensor.listeners.CloseEventListener] for bean with name 'closeEventListener' defined in ServletContext resource [/WEB-INF/application-context.xml]: problem with class file or dependent class; nested exception is java.lang.NoClassDefFoundError: com/espertech/esper/client/UpdateListener
Related cause: org.springframework.beans.factory.CannotLoadBeanClassException: Error loading class [com.oneops.sensor.listeners.ChannelDownListener] for bean with name 'channelDownListener' defined in ServletContext resource [/WEB-INF/application-context.xml]: problem with class file or dependent class; nested exception is java.lang.NoClassDefFoundError: com/espertech/esper/client/UpdateListener
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1202)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:403)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5077)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5591)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1095)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1957)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)

**Comment by nimkar** [comment]
This was raised by mistake. Not an issue.

**Comment by yrmallu** [comment]
@nimkar 
Hi Nilesh, 

  I'm facing the same issue now. Can you please let me know how to fix that ?
  
 Thanks

**Comment by nimkar** [comment]
The issue happened because I was building a new system as a non-privileged user. You need to do the whole build as root.

**Comment by yrmallu** [comment]
@nimkar I'm running as root user only but still getting the same error. 
Please let me know any changes or settings or needed
