### ISSUE TITLE
caught Exception in onMessage javax.jms.JMSException: mock 

### ISSUE THREAD

**Issue by yrmallu** [oneops/sensor#45]
2017-05-15 07:13:24 [main] INFO com.oneops.sensor.jms.SensorListener - caught Exception in onMessage
javax.jms.JMSException: mock
        at com.oneops.sensor.jms.SensorListener.onMessage(SensorListener.java:88)
        at com.oneops.sensor.jms.SensorListenerTest.testOnMessageExceptionCase(SensorListenerTest.java:64)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:842)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1166)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
        at org.testng.TestRunner.runWorkers(TestRunner.java:1178)
        at org.testng.TestRunner.privateRun(TestRunner.java:757)
        at org.testng.TestRunner.run(TestRunner.java:608)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
        at org.testng.SuiteRunner.run(SuiteRunner.java:240)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1158)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1083)
        at org.testng.TestNG.run(TestNG.java:999)
        at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
        at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
        at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
2017-05-15 07:13:24 [main] INFO com.oneops.sensor.listeners.OpsEventListener -  Recieved event for ciId :14144
2017-05-15 07:13:24 [main] WARN com.oneops.sensor.listeners.OpsEventListener - ignoring cid as it is not active14144
2017-05-15 07:13:24 [main] INFO com.oneops.sensor.listeners.OpsEventListener -  Recieved event for ciId :14144
2017-05-15 07:13:24 [main] WARN com.oneops.sensor.listeners.OpsEventListener - ignoring cid as it is not active14144
2017-05-15 07:13:24 [main] INFO com.oneops.sensor.ws.SensorWsController - Corrected TS for  1oldTs: 123456789 :correctedValue: 1234567890000
2017-05-15 07:13:24 [main] INFO com.oneops.sensor.ws.SensorWsController - Corrected TS for  2oldTs: 123456888 :correctedValue: 1234568880000
2017-05-15 07:13:24 [main] INFO com.oneops.sensor.ws.SensorWsController - Inserting fake events for mocked; ciId=0
2017-05-15 07:13:24 [main] INFO com.oneops.sensor.ws.SensorWsController - Inserting fake events for mocked; ciId=0
2017-05-15 07:21:18 [main] INFO com.oneops.sensor.Sensor - >>> Sensor initialization started.
2017-05-15 07:21:18 [main] INFO com.espertech.esper.core.service.EPServiceProviderImpl - Initializing engine URI 'default' version 4.4.0
2017-05-15 07:21:18 [main] INFO com.espertech.esper.core.thread.ThreadingServiceImpl - Starting pool Inbound with 16 threads
2017-05-15 07:21:18 [main] INFO com.espertech.esper.core.thread.ThreadingServiceImpl - Starting pool TimerExec with 16 threads
2017-05-15 07:21:18 [main] INFO com.espertech.esper.core.thread.ThreadingServiceImpl - Starting pool RouteExec with 16 threads
2017-05-15 07:21:18 [main] INFO com.espertech.esper.core.thread.ThreadingServiceImpl - Starting pool Outbound with 16 threads
2017-05-15 07:21:19 [main] INFO com.oneops.sensor.StmtBuilder - Statement Builder initialized with Max Duration: 5, ChannelDownInterval: 15
2017-05-15 07:21:19 [main] INFO com.oneops.sensor.StmtBuilder - Statement Builder initialized with Max Duration: 5, ChannelDownInterval: 15
2017-05-15 07:21:19 [main] INFO com.oneops.sensor.StmtBuilder - Statement Builder initialized with Max Duration: 5, ChannelDownInterval: 15
2017-05-15 07:21:19 [main] INFO com.oneops.sensor.StmtBuilder - Statement Builder initialized with Max Duration: 5, ChannelDownInterval: 15
2017-05-15 07:21:19 [main] INFO com.oneops.sensor.jms.OpsEventPublisher - Closing AMQ connection
2017-05-15 07:21:19 [main] INFO com.oneops.sensor.jms.SensorListener - caught Exception in onMessage
javax.jms.JMSException: mock
        at com.oneops.sensor.jms.SensorListener.onMessage(SensorListener.java:88)
        at com.oneops.sensor.jms.SensorListenerTest.testOnMessageExceptionCase(SensorListenerTest.java:64)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:842)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1166)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
        at org.testng.TestRunner.runWorkers(TestRunner.java:1178)
        at org.testng.TestRunner.privateRun(TestRunner.java:757)
        at org.testng.TestRunner.run(TestRunner.java:608)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
        at org.testng.SuiteRunner.run(SuiteRunner.java:240)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1158)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1083)
        at org.testng.TestNG.run(TestNG.java:999)
        at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
        at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
        at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

**Comment by mosabua** [comment]
Issues are migrated to Walmart JIRA and https://github.com/oneops/oneops
